name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        - cron:  '0 0 * * *'

jobs:
    php:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3]
                prefer: [lowest, stable]

        steps:
            - uses: actions/checkout@v2

            - name: Switch PHP
              run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

            - name: Show PHP version
              run: php -v

            - uses: actions/cache@v1
              with:
                  path: /home/runner/.composer/cache
                  key: composer-php.${{ matrix.php }}-prefer.${{ matrix.prefer }}-${{ github.sha }}
                  restore-keys: composer-php.${{ matrix.php }}-prefer.${{ matrix.prefer }}-

            - name: Update composer
              run: |
                  mkdir -p /home/runner/.composer/
                  sudo composer self-update --snapshot

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Composer Github Auth
              run: composer config -g github-oauth.github.com ${{ github.token }}

            - name: Update dependencies
              run: composer update --prefer-${{ matrix.prefer }} --prefer-dist --no-progress --no-suggest --no-scripts

    sylius:
        runs-on: ubuntu-latest

        env:
            # Run staging server while PR https://github.com/symfony/recipes-contrib/pull/913 not merged
            SYMFONY_ENDPOINT: https://flex.symfony.com/r/github.com/symfony/recipes-contrib/913

        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3]
                sylius: [1.5, 1.6, 1.7]
                exclude:
                    - php: 7.2
                      sylius: 1.7

        steps:
            - name: Remove HHVM
              run: sudo apt-get remove --auto-remove -y hhvm
              if: matrix.sylius == 1.3 || matrix.sylius == 1.4

            - name: Switch PHP
              run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

            - name: Show PHP version
              run: php -v

            - name: Setup timezone
              run: |
                  echo "date.timezone=UTC" >> /tmp/timezone.ini; \
                  sudo mv /tmp/timezone.ini /etc/php/${{ matrix.php }}/cli/conf.d/timezone.ini
            - uses: actions/checkout@v2
              with:
                  path: plugin

            - uses: actions/cache@v1
              with:
                  path: /home/runner/.composer/cache
                  key: composer-php.${{ matrix.php }}-sylius.${{ matrix.sylius }}.0-${{ github.sha }}
                  restore-keys: composer-php.${{ matrix.php }}-sylius.${{ matrix.sylius }}.0-

            - name: Update composer
              run: |
                  mkdir -p /home/runner/.composer/
                  sudo composer self-update --snapshot

            - name: Composer Github Auth
              run: composer config -g github-oauth.github.com ${{ github.token }}

            - name: Install Sylius-Standard
              run: |
                  composer create-project --prefer-dist --no-scripts --no-progress sylius/sylius-standard sylius "~${{ matrix.sylius }}.0"

            - name: Init database
              working-directory: ./sylius
              run: |
                  php bin/console doctrine:database:create --if-not-exists
                  php bin/console doctrine:migr:migr -n

            - name: Add path repository
              working-directory: ./sylius
              run: |
                  composer config repositories.plugin '{"type": "path", "url": "../plugin/"}'

            - name: Allow contrib recipes
              working-directory: ./sylius
              run: composer config extra.symfony.allow-contrib true

            - name: Install plugin
              working-directory: ./sylius
              run: |
                  composer req "synolia/sylius-scheduler-command-plugin:^1.0"

            - name: Update database schema
              working-directory: ./sylius
              run: |
                  php bin/console doctrine:migr:diff -vvv
                  php bin/console doctrine:migr:migr -n

            - name: Install Sylius
              working-directory: ./sylius
              run: php bin/console sylius:install -n

        services:
            mariadb:
                image: mariadb:latest
                ports:
                    - 3306:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
